name: ggwave_flutter
description: Flutter plugin for ggwave data-over-sound library
version: 0.0.2
homepage: https://github.com/tamal8730/ggwave_flutter

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.github.tamal8730.ggwave_flutter
        pluginClass: GgwaveFlutterPlugin
      ios:
        pluginClass: GgwaveFlutterPlugin
